#!/usr/bin/env bash
# Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
dis=1
while [ $dis -le 10 ]
do
    if [ $dis -eq 9 ]
    then
	echo "Best School"
	echo "Hi"
    else
	echo "Best School"
    fi
    
dis=$((dis + 1))  
done
